# Generated by Django 3.1.5 on 2021-01-19 20:33

from django.db import migrations, models


def load_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'group')
    admin = Group(name='Administrator')
    admin.save()

    moderator = Group(name='Moderator')
    moderator.save()

    user = Group(name='User')
    user.save()


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'group')
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_groups, delete_groups),
    ]
