# Generated by Django 3.1.5 on 2021-02-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_auto_20210120_0558'),
        ('cmsapp', '0002_initial_data'),
    ]

    operations = [
    ]
